mywebsite/apps/accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views
#import mywebsite.apps.public.urls as url_path

app_name="accounts"
urlpatterns = [
    path("profile", views.ProfileView.as_view(), name="profile"),
    # Django Auth
    path(
        "login",
        auth_views.LoginView.as_view(template_name="login.html"),
        name="login",
    ),
    path("logout", auth_views.LogoutView.as_view(), name="logout"),
]

mywebsite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views

from . import views
#import mywebsite.apps.public.urls as url_path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include('mywebsite.apps.public.urls')),
    path("accounts/", include('mywebsite.apps.accounts.urls')),

]

mywebsite/apps/accounts/models.py
from django.db import models
from django.contrib.auth.models import User

class UserPersona(models.Model):

    name= models.CharField(max_length=64, unique=True)
    normalized_name = models.CharField(max_length=64, unique=True)
    description = models.CharField(max_length= 200)

    def __str__(self):
        return self.name

# Create your models here.

class UserProfile(models.Model):
    #owner
    user=models.OneToOneField(User, on_delete=models.CASCADE, related_name="profile")
    is_full_name_displayed = models.BooleanField(default=True)

    #details
    bio = models.CharField(max_length=500, blank=True, null=True)
    website=models.URLField(max_length=200, blank=True, null=True)

mywebsite/apps/accounts/views.py
from django.views.generic.base import TemplateView
from django.contrib.auth.mixins import LoginRequiredMixin



class ProfileView(LoginRequiredMixin, TemplateView):
    template_name = "accounts/profile.html"

mywebsite/templates/about.html
{%extends 'base.html'%}

{%block title%} About {% endblock %}

{% block content %}
<h1>
    About
</h1>
{% endblock %}

mywebsite/templates/accounts/login.html
{%extends 'base.html'%}

{%block title%} About {% endblock %}

{% block content %}
<h2> Login </h2>
<form method="post">

    {% csrf_token %}
    {{form.as_p}}
    <button type="submit">Login</button>

</form>
{% endblock %}

mywebsite/templates/accounts/profile.html
{%extends 'base.html'%}

{%block title%} About {% endblock %}

{% block content %}
<h1>
    {{user.username}}'s profile
</h1>
{% endblock %}

mywebsite/templates/base.html
{% load static %}

<!-- templates/base.html-->
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>{%block title%} Metar Data{% endblock %}</title>

    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <!-- Font Awesome icons (free version)-->
    <script src="https://use.fontawesome.com/releases/v5.15.4/js/all.js" crossorigin="anonymous"></script>
    <!-- Google fonts-->
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css" />
    <link href="https://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic" rel="stylesheet" type="text/css" />
    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="{% static 'theme/css/styles.css' %}" rel="stylesheet" />

    <link href="{% static 'css/main.css' %}" rel="stylesheet" />
</head> 
<body>
    {%include 'navbar.html'%}
    <main id= "main">
        {% block content %}
        {% endblock %}
    </main>
    <!-- Bootstrap core JS-->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
    <!-- Core theme JS-->
    <script src="% static 'theme/js/scripts.js' %"></script>
    <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
    <!-- * *                               SB Forms JS                               * *-->
    <!-- * * Activate your form at https://startbootstrap.com/solution/contact-forms * *-->
    <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
    <script src="https://cdn.startbootstrap.com/sb-forms-latest.js"></script>
</body>
</html>

mywebsite/templates/contact.html
{%extends 'base.html'%}

{%block title%} Team {% endblock %}

{% block content %}
<h1>
    Team
</h1>
{% endblock %}

mywebsite/templates/index.html
{%extends 'base.html'%}
{% load static %}

{% block title%}Airport Metar Data Scrapper Project{% endblock%}

{% block content %}
<!-- <img class="masthead-avatar mb-5" src="{% static 'theme/assets/img/avataaars.svg' %}" alt="..." /> -->

<head>
    <title> Airport Metar Data Scrapper Project</title>
</head>

<link rel="stylesheet" href="{% static 'theme/css/styles.css' %}">

<body style="background-image: url('{% static 'theme/assets/img/chairs.jpg' %}'); background-repeat: no-repeat; background-size: 100%">

    <center>
        <h1> Airport Data Website</h1>
        <h2> Django webapp using PostgreSQL, Docker, and Beautiful Soup</h2>
        <hr/>
        <table border="1">
            <tr>
                <th>name</th>
                <th>airport_code</th>
                <th>temperature</th>
                <th>dewpoint</th>
                <th>pressure</th>
                <th>winds</th>
                <th>visibility</th>
                <th>ceiling</th>
                <th>clouds</th>
            </tr>
            {% for results in data%}
            <tr>
                <td>{{results.name}}</td>
                <td>{{results.airport_code}}</td>
                <td>{{results.temperature}}</td>
                <td>{{results.dewpoint}}</td>
                <td>{{results.pressure}}</td>
                <td>{{results.winds}}</td>
                <td>{{results.visibility}}</td>
                <td>{{results.ceiling}}</td>
                <td>{{results.clouds}}</td>
            </tr>
            {% endfor %}
        </table>
    </center>
</body>

{% endblock %}

mywebsite/templates/navbar.html
<!-- Navigation-->
<nav class="navbar navbar-expand-lg bg-secondary text-uppercase fixed-top" id="mainNav">
    <div class="container">
        <a class="navbar-brand" href="#page-top">Virtualization Two Project</a>
        <button class="navbar-toggler text-uppercase font-weight-bold hs-bg-primary text-white rounded" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            Menu
            <i class="fas fa-bars"></i>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ms-auto">
                {% url 'public:index' as index_url %}
                <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 rounded {% if request.path == index_url %}active{% endif %}" href="{{ index_url }}">Home</a></li>
                {% url 'public:about' as about_url %}
                <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 rounded {% if request.path == about_url %}active{% endif %}" href="{{ about_url }}">About</a></li>
                {% url 'public:contact' as contact_url %}
                <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 rounded {% if request.path == contact_url %}active{% endif %}" href="{{ contact_url }}">Team</a></li>
            </ul>
        </div>
    </div>
</nav>

<!-- 
<div>
    {% url 'public:index' as index_url %}
    <span>{% if request.path == index_url %}Home{% else %}<a href="{{ index_url }}">Home</a>{% endif %}</span>
    {% url 'public:about' as about_url %}
    <span>{% if request.path == about_url %}About{% else %}<a href="{{ about_url }}">About</a>{% endif %}</span>
    {% url 'public:contact' as contact_url %}
    <span>{% if request.path == contact_url %}Contact{% else %}<a href="{{ contact_url }}">Contact</a>{% endif %}</span>

    <span style="float:right">
        {% if user.is_authenticated%}
            {% url 'profile' as profile_url%}
            <span>Hi {% if request.path == profile_url%}{{user.username}}{% else %}<a href="{{profile_url}}">{{user.username}}</a>{% endif %}</span>
            <span><a href="{%url 'accounts:logout'%}">Logout</a></span>
        {% else %}
            <span><a href="{%url 'accounts:login'%}">Login</a></span>
        {% endif %}
    </span>
</div>
 -->